version: "3.8"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_publications
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_publications"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3021:3021"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    env_file:
      - ./backend/.env
    depends_on:
      - db_postgres
    entrypoint:
      [
        "sh",
        "-c",
        "until pg_isready -h db_postgres -U admin -d db_publications; do echo waiting for db; sleep 5; done; npm run build",
      ]

volumes:
  db_postgres_data:
