version: "3.8"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_publications
    volumes:
      - db_postgres_data:/var/lib/postgresql/data

volumes:
  db_postgres_data:
