version: "3.8"

services:
  db_postgres:
    image: postgres:15
    container_name: db_postgres
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_publications
    volumes:
      - db_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3021:3021"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
    env_file:
      - ./backend/.env
    depends_on:
      - db_postgres
    entrypoint: ["sh", "-c", "sleep 10 && npx prisma generate && npm run build"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3020:3020"
    volumes:
      - ./frontend:/usr/app
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

volumes:
  db_postgres_data:
